### ISSUE TITLE
[Bug]: Release v1.0.0 描述文本“的”、“地”使用错误

### ISSUE THREAD

**Issue by Snoopy1866** [adproqwq/LiteLoaderQQNT-QuickReply#1]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-QuickReply/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

NA

### LiteLoaderQQNT 版本

NA

### 本插件 版本

NA

### 插件检测更新API插件 版本

NA

### 运行环境

Windows

### 重现步骤

无需重现

### 期望的结果是什么？

调整 Release 文本

### 实际的结果是什么？

一条病句

### 补充说明（可选）

https://github.com/adproqwq/LiteLoaderQQNT-QuickReply/releases/tag/v1.0.0

正确使用示例：添加快捷键以更快**地**添加回复语

**Comment by adproqwq** [comment]
我说是输入法的问题，你信吗
