### ISSUE TITLE
[Feat]: 希望支持快捷长语

### ISSUE THREAD

**Issue by misaka10384** [adproqwq/LiteLoaderQQNT-QuickReply#4]
### 需要调整的功能内容

![Clip_2024-08-13_17-01-15](https://github.com/user-attachments/assets/97f5cefc-8de1-408a-b2d1-86489e07534e)
![Clip_2024-08-13_17-01-29](https://github.com/user-attachments/assets/c531064b-4f2b-4a24-8472-01ffa6020b47)
现在这个快捷回复不是一行一句话吗  希望能改一下  变成一个块  这个块视为一个整体 不会因为换行而分成两句话  
然后可以创建多个块来设置多个快捷短语   就跟记事本一样 一个记事本里面就是一个内容整体

**Comment by adproqwq** [comment]
有这个计划，预计将在近期完成

**Comment by adproqwq** [comment]
使用1.1.0，关于使用，请查看新的README
