### ISSUE TITLE
[Bug]: 单条消息过长时，配置页卡死

### ISSUE THREAD

**Issue by aknyzsd** [adproqwq/LiteLoaderQQNT-QuickReply#5]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-QuickReply/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.9.15-26909

### LiteLoaderQQNT 版本

1.2.1

### 本插件 版本

1.1.0

### 插件检测更新API插件 版本

1.7.1

### 运行环境

Windows

### 重现步骤

安装后就这样了

### 期望的结果是什么？

插件正常使用

### 实际的结果是什么？

![{E96630D8-4DD0-498A-B387-33986B58550B}](https://github.com/user-attachments/assets/a24b8995-e233-4ad1-ba99-8b2a33bb7586)
![{462C191C-0154-4CE7-A545-58344893D21D}](https://github.com/user-attachments/assets/21a9b9b0-6a06-4a83-b9e7-434f8df65ac5)
配置白屏无法设置，快捷回复窗口也白屏无法正常使用

**Comment by adproqwq** [comment]
我只是没适配深色模式。设置页那个白的是输入框，配置快捷回复语用的，得在那里配置才能在输入框那里显示。
怎么配置你自己看READNE

**Comment by aknyzsd** [comment]
感谢，不过发现在配置单条消息过于长时会卡死

**Comment by aknyzsd** [comment]
> 感谢，不过发现在配置单条消息过于长时会卡死

就无法退出那个配置窗口来保存配置

**Comment by adproqwq** [comment]
> 感谢，不过发现在配置单条消息过于长时会卡死

能否录制个视频或者动图？我看看表现是怎样的
