### ISSUE TITLE
[Feat]: 快捷回复菜单中显示的文本可以居中

### ISSUE THREAD

**Issue by LeafStarVincent** [adproqwq/LiteLoaderQQNT-QuickReply#6]
### 需要调整的功能内容

输入框右上角显示的文字默认都是靠左的不太美观）
希望设置有个开关能调显示的居中还是靠左
（不影响输入）

**Comment by adproqwq** [comment]
https://github.com/adproqwq/LiteLoaderQQNT-QuickReply/blob/main/src%2Fstyle%2Fglobal.css#L80-L80

将left改成center即可，该文件位于插件中的style文件夹中，自行修改即可
