### ISSUE TITLE
[Bug]: 可无限换行吗？我怎么第三行开始就不显示了

### ISSUE THREAD

**Issue by san-ren** [adproqwq/LiteLoaderQQNT-QuickReply#7]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经正确安装了前置插件作为依赖，问题依旧存在。
- [X] 我已经使用一个仅安装本插件及依赖插件的环境测试过，问题依旧存在。
- [X] 我已经尝试过删除该插件的配置文件并重启 QQ，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/adproqwq/LiteLoaderQQNT-QuickReply/issues) 中找过我要提出的问题，没有找到相同问题的 ISSUE。

### QQNT 版本

9.915

### LiteLoaderQQNT 版本

1.21

### 本插件 版本

1.1.1

### 插件检测更新API插件 版本

1.71

### 运行环境

Windows

### 重现步骤

回复语块内换行，自第三行开始不显示。仅显示前两行内容，或整条回复语都不显示

### 期望的结果是什么？

回复语块内可以任意换行

### 实际的结果是什么？

并不支持三行或三行以上的回复语

**Comment by adproqwq** [comment]
请将你设置的回复语块回复在下面

**Comment by san-ren** [comment]
> 请将你设置的回复语块回复在下面

[[能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行吗能无限换行]]
![image](https://github.com/user-attachments/assets/4754f0f1-8f69-4ee2-bccc-5e3a8a4cddb6)

**Comment by adproqwq** [comment]
这是为了防止回复语块过长导致候选菜单里能选择的项目太少设计的，超过一定长度就会隐藏，实际应该是不会截断的

**Comment by san-ren** [comment]
> 这是为了防止回复语块过长导致候选菜单里能选择的项目太少设计的，超过一定长度就会隐藏，实际应该是不会截断的

哦哈哈，是我肤浅了，竟然没反应过来是这样
